import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar/Navbar'
import NavLogo from '../components/NavBar/NavLogo'
import NavItem from '../components/NavBar/NavItem'
import NavDropDownItem from '../components/NavBar/NavDropDownItem'
import Alert from '../components/Alert'
import {useEffect, useState} from 'react'
// import styles from '../styles/Home.module.css'



export default function Home() {
  const [getURL,setURL] = useState("")
  const GETSOME = ()=>{
    fetch(getURL).then((response) => response.text())
    .then((data) => console.log(data));
  }
  const clickGETSOME = (event: any) => {
    setURL((old)=>event.target.value)
  }

  return (
    <>
      <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
            <Image src="/vercel.svg" className="d-inline-block align-text-top" width="50" height="50" alt="logo"/>
            Logo
            </a>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
              <li className="nav-item">
                <a className="nav-link active" aria-current="page" href="#">Home</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div className="container">
      
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <input type="text" onChange={clickGETSOME}></input>
        <button onClick={GETSOME}>GET SOME</button>
        <iframe src={getURL}></iframe>
      <NavBar logo ={<NavLogo/>} > 
        <NavItem label="hi" link="#" />
        <NavItem label="Boy" link="#" />
        <NavDropDownItem label="hi" link="#"/>
      </NavBar>
      <h1>Example heading <span className="badge bg-secondary">New</span></h1>
      <Alert color="primary" />
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </>
  )
}
